/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp3grupo3;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Ezequiel
 */
public class LoginDeCredenciales extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    public LoginDeCredenciales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jescritorio = new javax.swing.JDesktopPane();
        jpInicioDeSesion = new javax.swing.JPanel();
        jlInicioDeSesion = new javax.swing.JLabel();
        jpBotonesOcultarYVer = new javax.swing.JPanel();
        jBotonOcultar = new javax.swing.JButton();
        jBotonVer = new javax.swing.JButton();
        jpVentanaDeCredenciales = new javax.swing.JPanel();
        jlUsuario = new javax.swing.JLabel();
        jlContraseña = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpContraseña = new javax.swing.JPasswordField();
        jBotonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Credenciales");

        jpInicioDeSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlInicioDeSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlInicioDeSesion.setText("Inicio de sesion");

        javax.swing.GroupLayout jpInicioDeSesionLayout = new javax.swing.GroupLayout(jpInicioDeSesion);
        jpInicioDeSesion.setLayout(jpInicioDeSesionLayout);
        jpInicioDeSesionLayout.setHorizontalGroup(
            jpInicioDeSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioDeSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlInicioDeSesion))
        );
        jpInicioDeSesionLayout.setVerticalGroup(
            jpInicioDeSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioDeSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlInicioDeSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpBotonesOcultarYVer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBotonOcultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ezequiel\\Documents\\GitHub\\grupo3TP-3\\img\\icons7-ocultar-contraseña-50.png")); // NOI18N
        jBotonOcultar.setText("Ocultar");
        jBotonOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonOcultarActionPerformed(evt);
            }
        });

        jBotonVer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ezequiel\\Desktop\\iconos_netbeans\\iconos netbeans\\icons7-mostrar-contraseña-50.png")); // NOI18N
        jBotonVer.setText("Ver");
        jBotonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesOcultarYVerLayout = new javax.swing.GroupLayout(jpBotonesOcultarYVer);
        jpBotonesOcultarYVer.setLayout(jpBotonesOcultarYVerLayout);
        jpBotonesOcultarYVerLayout.setHorizontalGroup(
            jpBotonesOcultarYVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesOcultarYVerLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jBotonOcultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBotonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBotonesOcultarYVerLayout.setVerticalGroup(
            jpBotonesOcultarYVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesOcultarYVerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotonesOcultarYVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotonOcultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotonVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpVentanaDeCredenciales.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese las credenciales"));

        jlUsuario.setText("Usuario:");

        jlContraseña.setText("Contraseña:");

        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });

        jpContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpContraseñaActionPerformed(evt);
            }
        });

        jBotonRegistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ezequiel\\Documents\\GitHub\\grupo3TP-3\\img\\icons8-cliente-windows-48.png")); // NOI18N
        jBotonRegistrar.setText("Registrar");
        jBotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpVentanaDeCredencialesLayout = new javax.swing.GroupLayout(jpVentanaDeCredenciales);
        jpVentanaDeCredenciales.setLayout(jpVentanaDeCredencialesLayout);
        jpVentanaDeCredencialesLayout.setHorizontalGroup(
            jpVentanaDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVentanaDeCredencialesLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jpVentanaDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlContraseña)
                    .addComponent(jlUsuario))
                .addGap(18, 18, 18)
                .addGroup(jpVentanaDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVentanaDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfUsuario)
                        .addComponent(jpContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                    .addComponent(jBotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jpVentanaDeCredencialesLayout.setVerticalGroup(
            jpVentanaDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVentanaDeCredencialesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpVentanaDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlUsuario)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpVentanaDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlContraseña)
                    .addComponent(jpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jescritorio.setLayer(jpInicioDeSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jescritorio.setLayer(jpBotonesOcultarYVer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jescritorio.setLayer(jpVentanaDeCredenciales, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jescritorioLayout = new javax.swing.GroupLayout(jescritorio);
        jescritorio.setLayout(jescritorioLayout);
        jescritorioLayout.setHorizontalGroup(
            jescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotonesOcultarYVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jescritorioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpInicioDeSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpVentanaDeCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jescritorioLayout.setVerticalGroup(
            jescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jescritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpInicioDeSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpVentanaDeCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpBotonesOcultarYVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jescritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jpContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpContraseñaActionPerformed

    private void jBotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRegistrarActionPerformed
        // TODO add your handling code here:
        char[] contraseña = jpContraseña.getPassword();
        char[] contraseñaCorrecta = new char[]{'1','2','3','4','5','6','7','8'};
        if(jtfUsuario.getText().equalsIgnoreCase("alumno@ulp.edu.ar")&& Arrays.equals(contraseña, contraseñaCorrecta)){
            JOptionPane.showMessageDialog(this, "Inicio de sesion correcto");
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
        }
    }//GEN-LAST:event_jBotonRegistrarActionPerformed

    private void jBotonOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonOcultarActionPerformed
        // TODO add your handling code here:
        jpContraseña.setEchoChar('*');
    }//GEN-LAST:event_jBotonOcultarActionPerformed

    private void jBotonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonVerActionPerformed
        // TODO add your handling code here:
        jpContraseña.setEchoChar((char)0);
    }//GEN-LAST:event_jBotonVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDeCredenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDeCredenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDeCredenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDeCredenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDeCredenciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonOcultar;
    private javax.swing.JButton jBotonRegistrar;
    private javax.swing.JButton jBotonVer;
    private javax.swing.JDesktopPane jescritorio;
    private javax.swing.JLabel jlContraseña;
    private javax.swing.JLabel jlInicioDeSesion;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPanel jpBotonesOcultarYVer;
    private javax.swing.JPasswordField jpContraseña;
    private javax.swing.JPanel jpInicioDeSesion;
    private javax.swing.JPanel jpVentanaDeCredenciales;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
